wandb_version: 1

learning_rate:
  desc: null
  value: 0.003
min_lr:
  desc: null
  value: 1.0e-07
weight_decay:
  desc: null
  value: 1.0e-05
model:
  desc: null
  value: AttentionUnet
tile_size:
  desc: null
  value: 320
train_stride_step:
  desc: null
  value: 10
epochs:
  desc: null
  value: 30
train_bs:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686816552.844169
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 48
      - 49
      - 51
      - 53
      - 55
      - 63
      - 74
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.15.4
      6: 4.29.2
      8:
      - 5
